server:
  port: 80
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: cloud-order-service
  zipkin:
    base-url: http://192.168.117.155:9411
  sleuth:
    sampler:
      # 采样率介于0到1之间，则表示全部采集
      probability: 1

eureka:
  instance:
    instance-id: order80
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    register-with-eureka: true # 表示将自己注册进Eureka Server
    fetch-registry: true       # 表示从Eureka Server抓取已有的注册信息
    service-url:
      # 单机版
      # defaultZone: http://eureka7001.com:7001/eureka/
      # 集群版
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
