server:
  port: 80
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true # 表示将自己注册进Eureka Server
    fetch-registry: true       # 表示从Eureka Server抓取已有的注册信息
    service-url:
      # defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka  # 集群版
