server:
  port: 8004
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: cloud-provider-payment
  cloud:
    zookeeper:
      connect-string: 192.168.117.155:2181 # 虚拟机开启或者云服务器开启Zookeeper服务
