server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        # 服Nacos服务注册中心地址
        server-addr: 192.168.117.155:8848
    sentinel:
      transport:
        # 配置Sentinel Dashboard地址
        dashboard: 192.168.117.155:8858
        # 默认端口
        port: 8719
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.117.155:8848
            dataId: cloudalibaba-sentinel-service
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: '*'
