server:
  port: 8002
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud2020?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: KAG1823
    druid:
      initial-size: 5
      max-active: 10
      min-idle: 5
      max-wait: 60000
      time-between-connect-error-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 900000
      validation-query: SELECT 1 FROM DUAL

eureka:
  client:
    register-with-eureka: true # 表示将自己注册进Eureka Server
    fetch-registry: true       # 表示从Eureka Server抓取已有的注册信息
    service-url:
      # defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka  # 集群版
  instance:
    instance-id: payment8002
    prefer-ip-address: true # 访问路径可以显示IP地址

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: top.parak.springcloud.entity
  configuration:
    map-underscore-to-camel-case: true

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: top.parak.springcloud.entity
  global-config:
    banner: false
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
