server:
  port: 80
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: cloud-openfeign-order

eureka:
  client:
    register-with-eureka: false # 表示不将自己注册进Eureka
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka  # 集群版

# 设置feign客户端超时时间(Openfeign默认支持ribbon)
ribbon:
  # 指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000
